'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Hanbai.Common.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  ＭＳ Ｐゴシック に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property APP_FONT_NAME() As String
            Get
                Return ResourceManager.GetString("APP_FONT_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  販売管理システム に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CAP_APPLICATION() As String
            Get
                Return ResourceManager.GetString("CAP_APPLICATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  エラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CAP_ERROR() As String
            Get
                Return ResourceManager.GetString("CAP_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  保存しますか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MSG_COMMIT() As String
            Get
                Return ResourceManager.GetString("MSG_COMMIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  保存は失敗しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MSG_COMMIT_FAIL() As String
            Get
                Return ResourceManager.GetString("MSG_COMMIT_FAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  更新確定は成功しました。 に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MSG_COMMIT_OK() As String
            Get
                Return ResourceManager.GetString("MSG_COMMIT_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  販売管理エラー に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MSG_ERROR() As String
            Get
                Return ResourceManager.GetString("MSG_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  入力したデータを破棄します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MSG_ROLLBACK() As String
            Get
                Return ResourceManager.GetString("MSG_ROLLBACK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  取消しました に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property MSG_ROLLBACK_SUCCESS() As String
            Get
                Return ResourceManager.GetString("MSG_ROLLBACK_SUCCESS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
